keys:
  # user
  - &iivusly '63D9C29CB7C1026401784A763BF2BE13BFC9B4EB!'
  # system
  - &nixos-server 'age1gdx3xf3tpcsletrgmnm7dghyvq9v8kekreprt95fpcptzta644dsvpmvnq'
  - &macbookpro   'age1rj8zgx8zzdjqkv08z9zarqhv3gre7juqvyjkjyak37t22w6eppvql9jvt9'
creation_rules:
  - path_regex: 'secrets/[^/]+\.yaml$'
    key_groups:
    - pgp:
      - *iivusly
      age:
      - *nixos-server
      - *macbookpro
  - path_regex: 'modules/home/secrets.yaml$'
    key_groups:
    - pgp:
      - *iivusly
      age:
      - *macbookpro
  - path_regex: 'modules/server/secrets.yaml$'
    key_groups:
    - pgp:
      - *iivusly
      age:
      - *nixos-server
