tailscale:
    nixos_server: ENC[AES256_GCM,data:YeeDxYQcO1572ssgphPUoFA6x5wdpQTTP9kVriXrMVhSyWnof0lKVux/ptpSnBlczMNZV/WNWnTy+FiexwU=,iv:l0J4DoVEOOYPnsYZ+TYcbsak/incXjDH0S9EnumzWE0=,tag:pezQbktJovVhecgQb7M9mg==,type:str]
    containers:
        navidrome: ENC[AES256_GCM,data:anxqIT6AlKLB05jOeUo0mMGVrTchKs9ObL0Hm0sQR2BGtwxjW+u9cFT4Kr0hCF33WDS7V08l133fhvK34Q==,iv:QsGdE30rE2U8FPD35WwEWvxy9RcVRlI+k8zhRViC2Bc=,tag:ekW1MdFTxmpiYFeEM17JZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQXdKRUFxSVJTZVdJNU5U
            TndyUUFFOS9WSjYwK0x4QTN0bEJteTg3S0dBClc2blNiTWtvb002OC96VitiVU1a
            bnppOTZIRnhXT1NBRzBuN1hTSmxqWk0KLS0tIDVUZFJzQ1UvdlJsQzBZRUdqRXQv
            dFRnelArenhwYStkS2JaTVBPL05VdW8KXJB50GKNuEHqpFLfA7KGqFeDRggi8umn
            keRaGuNN6/oI5OsXBYxMeLX0jdve69wuBC+TewTiloyMHMzJaWP5Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gdx3xf3tpcsletrgmnm7dghyvq9v8kekreprt95fpcptzta644dsvpmvnq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdU5SRUVBeHM3T2xTamth
            ZnhEbnhqK1k2d1ZZTzdXbnRTejFETTAwNkh3ClhRVkdUOHc5VWJFSlI1VHB5Qi9q
            cnIrZWV2d0dzQllndjVqVWo2bXZhbTAKLS0tIDAxNVFOZ3lGbCtBbFBEaC93d3Rl
            WW5JdHN3YWEvSlRzR0ltSlJvZXdhOTgKEnSi+K7b74DAijSKKRjdsehR7OKC/Kpn
            9J1jpw7H7KSpTu6p6auDMGAci2Rcr0q3KPZbe7VdHJtsMWeUJtCasQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rj8zgx8zzdjqkv08z9zarqhv3gre7juqvyjkjyak37t22w6eppvql9jvt9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU29YL2d1UkdJSEJQemdJ
            TjZzV0NaaGdMSkQ5TlZEV2VRMUd4VUFKdWowCjZNZUlDeTEvUU1BYmc4aHNCQ0JK
            SktobGFEdi9HWHhrVmo3NG9FWHYrc3cKLS0tIFhKTGprU0V2K215SkYzZEpxYmxQ
            VWNnSXYvZEgyMWEzSmdFNDhUaDl6VlEKRYSW/l9GU2pInb2zMWflRnGqWcI4gjAZ
            b6pfYqBnTuRjH2e+z4Bi86flLVhZJOl+KA2S6mK9ns1JcoqTyyU3FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmkcmpa6qgk3rlv0vmqhg9crqnqfg482veucjc6evd822nfpeyqsc3agyf
    lastmodified: "2026-01-13T18:50:49Z"
    mac: ENC[AES256_GCM,data:WTWR/8LBM4/K2lyPOnTq+wNnbBPRR4VS2o+S0b/Tgm6YWTIyepixAmbZVS1D/xVr+FyRbunC0PnfDsKdtngdiLacoqkI7MHitMEFvNnxcZCh/e6nm/BAtJPdC3HKXU5ut73rnQlBN4DkLsodyHUZk0iOC7oRn8Eg/wjiKyXX8Js=,iv:r0Fk0RrZjjOS8Mo7a/lSbutRE0FhYBm3n3a/h2OFKUY=,tag:pTbWrVzwVJBSVcEVY48OkQ==,type:str]
    pgp:
        - created_at: "2026-06-23T23:28:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DO/K+E7/JtOsSAQdAtQK1JPOqNb7rqeWDXm4SpOhUByFk+Lo+Ewbpp22ZyG0w
            Nu72o7LjAmtTscZTT+ei+sdDkuos7syImb8Eke6pPVsboE7tGlnZiwLnRkivRXnb
            0l4B15L3mkANL4z8lsS0ARfoX1xjuFJTjMyftWBL57xOf9GJ8k67Kn1ufrA92p4/
            LWzQtfvt2KVFpVxSq2W2Hzaix7SmiuTlhU6+sk09MZyAukiX/gmtNwoc7FtQtcWy
            =CzQ4
            -----END PGP MESSAGE-----
          fp: 63D9C29CB7C1026401784A763BF2BE13BFC9B4EB!
    unencrypted_suffix: _unencrypted
    version: 3.11.0
