nixos-server:
    password: null
tailscale:
    nixos_server: ENC[AES256_GCM,data:YeeDxYQcO1572ssgphPUoFA6x5wdpQTTP9kVriXrMVhSyWnof0lKVux/ptpSnBlczMNZV/WNWnTy+FiexwU=,iv:l0J4DoVEOOYPnsYZ+TYcbsak/incXjDH0S9EnumzWE0=,tag:pezQbktJovVhecgQb7M9mg==,type:str]
    containers:
        navidrome: ENC[AES256_GCM,data:anxqIT6AlKLB05jOeUo0mMGVrTchKs9ObL0Hm0sQR2BGtwxjW+u9cFT4Kr0hCF33WDS7V08l133fhvK34Q==,iv:QsGdE30rE2U8FPD35WwEWvxy9RcVRlI+k8zhRViC2Bc=,tag:ekW1MdFTxmpiYFeEM17JZA==,type:str]
sops:
    age:
        - recipient: age193jzp6mg5v789d786vrh5hyafyq2y6zs8sts3y2s2q74mxxnpqmqvguxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeGFRQVlnVHlWUkJSSndk
            VngrNzl1b1YyWGhvNEl4OWFRMUcvenJOSTAwCi9mclpickFKYVRnem5SU2xkeVV4
            V0FaOHZhb3c0RG1mL1VvcVJNTVVDWjgKLS0tIERVVG94NUI5UHpYdmZ3QVp0Rm1y
            RkdyQnhlbXk3MlpmTDZqMENMTlVnVFEKgT9zhLfIkareO1VNMzZbV+wDncDZSbcS
            UlwaJbWPeNU3UVXZsUEooHWWMlX+8+kefUUME6s5jAf8vuioeUvu8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rj8zgx8zzdjqkv08z9zarqhv3gre7juqvyjkjyak37t22w6eppvql9jvt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TjVqQTRCcHBWTUVwOHM3
            OTBWQkUyUWlscUZjckZtYURZZklFa1B3Um1NCnQxcEFBM2FCY04yTXlVYXJwSnIr
            L3VqdEVFS1d0RlErd0RyTEZGb1JSeFEKLS0tIGNYckgxU3NZRFhGTFZCcU43ZVFN
            ZkRIUFVNanhyRjc0bTVmZVFLR21TdU0K28JVVj9xjvpYofRBs8Bn2GsnUPi2kqXu
            Fdhk3TTCNDbnoGfvYlmxit5BK1zOvA7V08cEfTJSJc7vxVNVJCfyiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T18:44:57Z"
    mac: ENC[AES256_GCM,data:NC2W5PSlm5vBD/F2HNyKtjn8xo/Ndu6aJMyaFyiTOaOEByuWYsLrbpG0/a71Ijj39zPoYiE+MiR02XMKqmvRYqD0cS5t9t1LzcYNmLkLDvtv/uIKOgUCa48cEQbWSiinfPMsK+U5imfs+Uu9Lj8oEQDc0lnUxbFnHlHSVIV9SsI=,iv:ubhKXbes7qcq67PxP8ydfF8oyTm1JpsIn1D4Sxrc3RI=,tag:rIAVy0L/ISEYKaJ7yo0fCg==,type:str]
    pgp:
        - created_at: "2025-12-03T00:11:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DO/K+E7/JtOsSAQdAHbZnMYkntjOO1DfdIMya63jhicO5Bj+L7GgjD1CGXmQw
            BDVbkUN9/MqChbl8EKvzOx2jaGpsdZpKH+USZXyWcmCAHmrvrTMsNTBZkZX9/Lzw
            0l4BKwyTkUwUOBNq8V+qCRtPuIXYKlFMha6uScr9iCLao9WlFJMdnvw0l4GrdMo6
            KaHdiLXl0AtM1xCfV4YtlWictqf6i+JyTsXkWZbOwKMYTKIeL1LCTZFBGk3CYPi0
            =fr7A
            -----END PGP MESSAGE-----
          fp: 63D9C29CB7C1026401784A763BF2BE13BFC9B4EB!
    unencrypted_suffix: _unencrypted
    version: 3.11.0
