tailscale:
    nixos_server: ENC[AES256_GCM,data:YeeDxYQcO1572ssgphPUoFA6x5wdpQTTP9kVriXrMVhSyWnof0lKVux/ptpSnBlczMNZV/WNWnTy+FiexwU=,iv:l0J4DoVEOOYPnsYZ+TYcbsak/incXjDH0S9EnumzWE0=,tag:pezQbktJovVhecgQb7M9mg==,type:str]
    containers:
        navidrome: ENC[AES256_GCM,data:anxqIT6AlKLB05jOeUo0mMGVrTchKs9ObL0Hm0sQR2BGtwxjW+u9cFT4Kr0hCF33WDS7V08l133fhvK34Q==,iv:QsGdE30rE2U8FPD35WwEWvxy9RcVRlI+k8zhRViC2Bc=,tag:ekW1MdFTxmpiYFeEM17JZA==,type:str]
sops:
    age:
        - recipient: age1h7m55qzcjsdz8gg2etn3qaeeaf2hg0evymqexqt37dnc4lf2kplqjdvdp8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUmRvWkE4UG5ZMzJuV2Yy
            L0FZQWt1RnpDaXRETHlmUGhISGs4ZUNkYkFnCjd0RXFBV3FQR0cvcXN0aXpVK3pq
            QUJFMlUwNnlCK2lNQ1FVTk1QTGtVZW8KLS0tIGJtUUJMRWx4dkFveXFGWjdOc2ho
            bU5ETjcxUGFwQnJYeVBXNzNpTnRQd2cKzrk9E6In38douVjQK825aKjdfGyCfQIx
            rtVGVFYIW2wHCYqZzg595Oq0k2fqoKwAK5XL2d1SdxSyOUNCh47GAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rj8zgx8zzdjqkv08z9zarqhv3gre7juqvyjkjyak37t22w6eppvql9jvt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bTNWak1mY3NsS3R2dkd2
            Qkc3S2FabE1PeFArQnlqamxBZEptbnpBK0VRCjJtL1NkUjN2QUFka1pkdFd3TzRB
            NERhY1B3amgxWmJVSW9HQ2x4aXU3UTQKLS0tIE10TXhadElNZXhSbFV1Wk52K0hD
            NjdLaEphYllkZDRZcEdEZmliVEdHWHcKyKXksmygbXqh1IjRBFTNDqNcMObntszi
            OmykiIAJLzg7NS9aQImVonGgCQtTjY1hwoJKtEYMjFh3/1+hjYEoQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T18:50:49Z"
    mac: ENC[AES256_GCM,data:WTWR/8LBM4/K2lyPOnTq+wNnbBPRR4VS2o+S0b/Tgm6YWTIyepixAmbZVS1D/xVr+FyRbunC0PnfDsKdtngdiLacoqkI7MHitMEFvNnxcZCh/e6nm/BAtJPdC3HKXU5ut73rnQlBN4DkLsodyHUZk0iOC7oRn8Eg/wjiKyXX8Js=,iv:r0Fk0RrZjjOS8Mo7a/lSbutRE0FhYBm3n3a/h2OFKUY=,tag:pTbWrVzwVJBSVcEVY48OkQ==,type:str]
    pgp:
        - created_at: "2026-01-13T18:54:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DO/K+E7/JtOsSAQdAtxVpQSnbDkL1wRF7dSGVT6WAYDQfUqSVyPO6Vt4i0U4w
            tsclHt3IP/0k1ofUX7/7IuCrH2fBhi/izXWVZxRxhNv3J2HHTVEMjqLFhktgloO7
            0l4BxVrdGorOK6Lepl+AA5HN0X/UlEdOQifkz6IaeDYyPWNuX2utQAGuUrp+AoF7
            t/B1iq9EzDLJ+C8s3MtrsFXusMrQACi5lEblGZsAmaNvo6pnE524nHfjok7J8vAg
            =IBBe
            -----END PGP MESSAGE-----
          fp: 63D9C29CB7C1026401784A763BF2BE13BFC9B4EB!
    unencrypted_suffix: _unencrypted
    version: 3.11.0
